baseurl: ""

title      : evo Umhlanga - Bond Origination & Home Loans Expert in Umhlanga, Durban, Kwazulu-Natal
email      : tash.pillay@evogroup.co.za
description: Contact Kimeshni or Tash Pillay from evo Umhlanga to help you with your home loan. We are seasoned property professionals and specialize in mortgages and property finance with years of experience. Our experience ranges from sales to finance and out focus is bonds, homeloans and origination. evo Umhlanga is committed to excellent client service, building long-term relationships.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: xxxxxxx

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/evo umhlanga logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: evo Homeloans

company: evo Umhlanga 

url: https://evohomeloans.co.za/bond-originators/umhlanga-rocks/

address: G5 Corner of Zenith & Equinox Drive, Umhlanga Rocks, 4320
