baseurl: "https://www.evoxxx.co.za"

title      : evo  xxx - Bond Origination & Home Loans Expert in Gqeberha Port Elizabeth PE
email      : x.xx@evogroup.co.za
description: Contact xxx xxxxxxxx from xxxxxxx, xxxxxxx to help you with home loan. xxxxxx is a seasoned property professional in mortgages and property finance with 28 years of experience. xxxxxx's experience ranges from sales to finance and she specializes in bonds, homeloans and origination. xxxxx is committed to excellent client service, building long-term relationships..
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: xxxxxxx

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: evo Group

company: evo xxx xxxxxx

url: www.xxxxxx.co.za

address: 21 xxxx Road, xxx xxxxx, xxxxxxx (xxxx xxxxxxx), 6070
